// export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY"
export const SET_FILTER = "SET_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const INITIALIZE_CATALOG = "INITIALIZE_CATALOG";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
